import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faHouseChimney,
  faSun,
  faMoon,
  faBars,
  faXmark,
  faBell,
  faMagnifyingGlass,
  faBolt,
  faShieldHalved,
  faCreditCard,
  faKey,
  faFileSignature,
  faHandshake,
  faClipboardList,
  faLocationDot,
  faStar,
  faArrowRightLong,
  faLeaf,
  faLock,
  faUser
} from '@fortawesome/free-solid-svg-icons'
import { faFacebook, faInstagram, faLinkedin, faTwitter } from '@fortawesome/free-brands-svg-icons'

library.add(
  faHouseChimney,
  faSun,
  faMoon,
  faBars,
  faXmark,
  faBell,
  faMagnifyingGlass,
  faBolt,
  faShieldHalved,
  faCreditCard,
  faKey,
  faFileSignature,
  faHandshake,
  faClipboardList,
  faLocationDot,
  faStar,
  faArrowRightLong,
  faLeaf,
  faLock,
  faUser,
  faFacebook,
  faInstagram,
  faLinkedin,
  faTwitter
)
